version: '3'

services:
  app:
    image: christianp93/express-awss:latest
    container_name: express-awss
    restart: always
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production